### ISSUE TITLE
Laravel 7 support

### ISSUE THREAD

**Issue by it-can** [creitive/laravel6-breadcrumbs#2]
Can you support Laravel 7?

**Comment by bonny** [comment]
I was looking for a version for Laravel 7 but then I found https://github.com/creitive/breadcrumbs and just installed that and everything just continued to work. Maybe worth trying.

**Comment by HasanAlyazidi** [comment]
Let's find a way to support Laravel 7 and the upcoming Laravel 8 please.

**Comment by levacic** [comment]
Apologies for the unreasonable delay on this, it was a weird year.

A new `creitive/laravel-breadcrumbs` package is now available:

- Packagist: https://packagist.org/packages/creitive/laravel-breadcrumbs 
- GitHub: https://github.com/creitive/laravel-breadcrumbs

It's basically the same package as this one, but references Laravel versions 7, 8, and 9 in its `composer.json` file.

The fact that we have so many integration packages that do the same thing is just a legacy thing, due to this project initially being developed way back for Laravel 4 - but moving forward it doesn't make sense to have separate packages for different Laravel versions, as this package is basically just a service provider + facade, which is why the new package is just `laravel-breadcrumbs`. Moving forward, we'll handle version compatibility via `composer.json` in that repo.
